#Action Goal

string location
---
#Action Result

bool success
string message
---
#Action Feedback

int8 ROBOT_IDLE = 10
int8 GO_TO_FRONTDESK = 20
int8 ARRIVAL_AT_FRONTDESK = 30
int8 WAITING_FOR_FRONTDEST = 40
int8 IN_DELIVER = 50
int8 COMPLETE_ALL_DELIVERY = 60
int8 RETURN_TO_DOCK = 70
int8 COMPELTE_RETURN = 80

int8 order_status
int8 robot_status