string location
---
bool success
string message
---
int8 ROBOT_IDLE = 10
int8 ARRIVAL_AT_FRONT = 20
int8 START_DELIVERY = 30
int8 ON_DELIVER = 40
int8 COMPLETE_ALL_DELIVERY = 50
int8 RETURN_TO_DOCK = 60
int8 COMPELTE_RETURN = 70

int8 order_status
int8 robot_status